#!/usr/bin/env python3

import argparse, os
import pandas as pd
pd.options.mode.copy_on_write = True


# This Script reads in the output from epitopeLevelScores.py and creates a subset version of the output, which only includes the subset of epitopes that meet user defined criteria.

def main():

	parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)

	reqArgs = parser.add_argument_group('required arguments')
	# Note that these arguments are added directly to the new argument group "reqArgs", not "parser" 
	reqArgs.add_argument('-i', '--input',  help='Input file. It should be an epitope score file generated by epitopeLevelScores.py.', required=True)
	reqArgs.add_argument('-o', '--output',  help='Name for output file.', required=True)
	reqArgs.add_argument('-z', '--zThresh', type=float,  help='Minimum MaxZ score threshold for an individual to be considered reactive at a given epitope.', required=True)
	reqArgs.add_argument('-n', '--numReactive', type=int,  help='Minimum number of reactive samples.', required=True)
	
	opts = parser.parse_args()

	# Read in input file
	df = pd.read_csv(opts.input, sep="\t", header=0)

	print(f"Input contains {len(set(df["Epitope"]))} epitopes")

	
	# Step through each epitope and make sure it meets the minimum requirements
	episForOutput=[]
	for epi in set(df["Epitope"]):
		epiDF = df[df["Epitope"]==epi]
		nr = sum(epiDF["MaxZ"]>=opts.zThresh)
		if nr >= opts.numReactive:
			episForOutput.append(epi)
				
	# Generate new version of the input dataframe that only includes the epitopes that met the requirements
	subset_df = df[[e in episForOutput for e in df['Epitope']]].copy()
	subset_df.to_csv(opts.output, sep="\t", index=False)
	
	
	print(f"{len(episForOutput)} epitopes met specified criteria:")
	print(episForOutput)

#----------------------End of main()



###------------------------------------->>>>	

if __name__ == "__main__":
	main()

