name: C++ CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'log level'
      environment:
      tags:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: [ ubuntu-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
