name: C++ CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'log level'
      environment:
      tags:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: [ ubuntu-latest, macos-latest ]

    steps:
    - name: configure
      run:
        sudo apt update
        sudo apt install zlib1g
        sudo apt install zlib1g-dev
        sudo apt install -y libboost-all-dev
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make pepsirf_test

    - name: configure
      run:
        cd build
        ./pepsirf_test